---
- name: Add iptables init script
  copy: src=iptables dest=/etc/init.d/iptables mode=0700

- name: Add iptables script
  template: src=iptables_script.sh dest=/root/iptables_script.sh mode=0700

- name: Enable iptables init script
  command: update-rc.d iptables defaults

- name: Create /var/lib/iptables
  file: path=/var/lib/iptables state=directory

- name: Save iptables
  command: /etc/init.d/iptables save inactive

- name: Run iptables script
  command: /root/iptables_script.sh
